version: "3.8"
# volumes:
#   datafiles:
  
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017

    ## AINDA NAO ENTENDI MUITO BEM ESTA CENA DOS USERS 
    ## SE USARMOS ISTO DEMOS DE USAR AUTENTICAÇAO PARA PEDIR À DB
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    #   - MONGO_INITDB_DATABASE=mongodb
    #   - MONGO_DB_USERNAME=grupo
    #   - MONGO_DB_PASSWORD=estiado

    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/data:/data/db

    networks:
      - main-network

    # SO ESTOU A GUARDAR POR GUARDAR QUE ESTA LINHA FEZ ME PERDER A BELEZA
    # command: ["--bind_ip", "localhost"]

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - main-network


  web:
    build: ./lockedin
    image: lockedin
    container_name: lockedin
    restart: on-failure
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - 5001:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=lockedin
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=mongodb
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=grupo
      - SPRING_DATA_MONGODB_PASSWORD=estiado
      - SPRING_DATA_MONGODB_DATABASE=mongodb
      - SPRING_RABBITMQ_HOST=rabbitmq

    networks:
      - main-network

  reactclient:
    build: ./frontend
    container_name: reactclient
    ports:
      - 3001:3000
    stdin_open: true
    depends_on:
      - web
    restart: unless-stopped
    image: lockedin-frontend

networks:
  main-network:
    external:
      name: lockedin-network